import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-order',
  templateUrl: './order.component.html',
  styleUrls: ['./order.component.scss']
})
export class OrderComponent implements OnInit {

  bills = [
    {
      dishName: 'Salted Pasta With Mushroom Sauce',
      kotId: 79,
      orderType: 'Dine-in',
      billPrintDate: '11/22/2022',
      customerName: 'Rajesh Sharma',
      customerPhone: 998685869,
      item: 5,
      status: 'Used In Bill',
      estimatedTime: '45 min',
      orderRecieve: '22:55',
    },
    {
      dishName: 'Salted Pasta With Mushroom Sauce',
      kotId: 79,
      orderType: 'Dine-in',
      billPrintDate: '11/22/2022',
      customerName: 'Rajesh Sharma',
      customerPhone: 998685869,
      item: 5,
      status: 'Used In Bill',
      estimatedTime: '45 min',
      orderRecieve: '22:55',
    },
    {
      dishName: 'Salted Pasta With Mushroom Sauce',
      kotId: 79,
      orderType: 'Dine-in',
      billPrintDate: '11/22/2022',
      customerName: 'Rajesh Sharma',
      customerPhone: 998685869,
      item: 5,
      status: 'Used In Bill',
      estimatedTime: '45 min',
      orderRecieve: '22:55',
    },
    {
      dishName: 'Salted Pasta With Mushroom Sauce',
      kotId: 79,
      orderType: 'Dine-in',
      billPrintDate: '11/22/2022',
      customerName: 'Rajesh Sharma',
      customerPhone: 998685869,
      item: 5,
      status: 'Used In Bill',
      estimatedTime: '45 min',
      orderRecieve: '22:55',
    },
    {
      dishName: 'Salted Pasta With Mushroom Sauce',
      kotId: 79,
      orderType: 'Dine-in',
      billPrintDate: '11/22/2022',
      customerName: 'Rajesh Sharma',
      customerPhone: 998685869,
      item: 5,
      status: 'Used In Bill',
      estimatedTime: '45 min',
      orderRecieve: '22:55',
    },
    {
      dishName: 'Salted Pasta With Mushroom Sauce',
      kotId: 79,
      orderType: 'Dine-in',
      billPrintDate: '11/22/2022',
      customerName: 'Rajesh Sharma',
      customerPhone: 998685869,
      item: 5,
      status: 'Used In Bill',
      estimatedTime: '45 min',
      orderRecieve: '22:55',
    },
    {
      dishName: 'Salted Pasta With Mushroom Sauce',
      kotId: 79,
      orderType: 'Dine-in',
      billPrintDate: '11/22/2022',
      customerName: 'Rajesh Sharma',
      customerPhone: 998685869,
      item: 5,
      status: 'Used In Bill',
      estimatedTime: '45 min',
      orderRecieve: '22:55',
    },
    {
      dishName: 'Salted Pasta With Mushroom Sauce',
      kotId: 79,
      orderType: 'Dine-in',
      billPrintDate: '11/22/2022',
      customerName: 'Rajesh Sharma',
      customerPhone: 998685869,
      item: 5,
      status: 'Used In Bill',
      estimatedTime: '45 min',
      orderRecieve: '22:55',
    },
    {
      dishName: 'Salted Pasta With Mushroom Sauce',
      kotId: 79,
      orderType: 'Dine-in',
      billPrintDate: '11/22/2022',
      customerName: 'Rajesh Sharma',
      customerPhone: 998685869,
      item: 5,
      status: 'Used In Bill',
      estimatedTime: '45 min',
      orderRecieve: '22:55',
    },
  ]
  widgets = [
    {
      orderNo: 79,
      tableNo: 79,
      customerName: 'Rajesh Sharma',
      dishName: 'Caser Salad',
      estimatedTime: '45 min',
      topping: 'Chix',
      extra: 'Dressing on Slide',
      timeLeft: '6M:47S',
      status: 'In Making',
    },
    {
      orderNo: 79,
      tableNo: 79,
      customerName: 'Rajesh Sharma',
      dishName: 'Caser Salad',
      estimatedTime: '45 min',
      topping: 'Chix',
      extra: 'Dressing on Slide',
      timeLeft: '6M:47S',
      status: 'In Making',
    },
    {
      orderNo: 79,
      tableNo: 79,
      customerName: 'Rajesh Sharma',
      dishName: 'Caser Salad',
      estimatedTime: '45 min',
      topping: 'Chix',
      extra: 'Dressing on Slide',
      timeLeft: '6M:47S',
      status: 'In Making',
    },
    {
      orderNo: 79,
      tableNo: 79,
      customerName: 'Rajesh Sharma',
      dishName: 'Caser Salad',
      estimatedTime: '45 min',
      topping: 'Chix',
      extra: 'Dressing on Slide',
      timeLeft: '6M:47S',
      status: 'In Making',
    },
    {
      orderNo: 79,
      tableNo: 79,
      customerName: 'Rajesh Sharma',
      dishName: 'Caser Salad',
      estimatedTime: '45 min',
      topping: 'Chix',
      extra: 'Dressing on Slide',
      timeLeft: '6M:47S',
      status: 'In Making',
    },
    {
      orderNo: 79,
      tableNo: 79,
      customerName: 'Rajesh Sharma',
      dishName: 'Caser Salad',
      estimatedTime: '45 min',
      topping: 'Chix',
      extra: 'Dressing on Slide',
      timeLeft: '6M:47S',
      status: 'In Making',
    },
    {
      orderNo: 79,
      tableNo: 79,
      customerName: 'Rajesh Sharma',
      dishName: 'Caser Salad',
      estimatedTime: '45 min',
      topping: 'Chix',
      extra: 'Dressing on Slide',
      timeLeft: '6M:47S',
      status: 'In Making',
    },
  ]
  items = [
    {
      tableNo: 'C34',
      waiterName: 'Sujit',
      id: '#579',
      dishName: 'Caser Salad',
      peopleOdered: 4,
      topping: 'Chix',
      extra: 'Dressing on Slide',
      timeLeft: '6M:47S',
      time: '10:34 PM',
    },
    {
      tableNo: 'C34',
      waiterName: 'Sujit',
      id: '#579',
      dishName: 'Caser Salad',
      peopleOdered: 4,
      topping: 'Chix',
      extra: 'Dressing on Slide',
      timeLeft: '6M:47S',
      time: '10:34 PM',
    },
    {
      tableNo: 'C34',
      waiterName: 'Sujit',
      id: '#579',
      dishName: 'Caser Salad',
      peopleOdered: 4,
      topping: 'Chix',
      extra: 'Dressing on Slide',
      timeLeft: '6M:47S',
      time: '10:34 PM',
    },
    {
      tableNo: 'C34',
      waiterName: 'Sujit',
      id: '#579',
      dishName: 'Caser Salad',
      peopleOdered: 4,
      topping: 'Chix',
      extra: 'Dressing on Slide',
      timeLeft: '6M:47S',
      time: '10:34 PM',
    },
    {
      tableNo: 'C34',
      waiterName: 'Sujit',
      id: '#579',
      dishName: 'Caser Salad',
      peopleOdered: 4,
      topping: 'Chix',
      extra: 'Dressing on Slide',
      timeLeft: '6M:47S',
      time: '10:34 PM',
    },
    {
      tableNo: 'C34',
      waiterName: 'Sujit',
      id: '#579',
      dishName: 'Caser Salad',
      peopleOdered: 4,
      topping: 'Chix',
      extra: 'Dressing on Slide',
      timeLeft: '6M:47S',
      time: '10:34 PM',
    },
    {
      tableNo: 'C34',
      waiterName: 'Sujit',
      id: '#579',
      dishName: 'Caser Salad',
      peopleOdered: 4,
      topping: 'Chix',
      extra: 'Dressing on Slide',
      timeLeft: '6M:47S',
      time: '10:34 PM',
    },
  ]

  constructor() { }

  ngOnInit(): void {
  }

}
